language: android
dist: trusty
jdk:
  - openjdk8
android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-29.0.2
    - android-29
  licenses:
    - '.+'
before_install:
  - yes | sdkmanager "platforms;android-29"
  - yes | sdkmanager "build-tools;28.0.3"
  - chmod +x gradlew
script:
  - ./gradlew build